# Generated by Django 4.2.5 on 2024-01-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_post_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='borrower',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
