# Generated by Django 4.2.5 on 2024-01-06 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0009_alter_post_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='已預約'),
        ),
        migrations.AddField(
            model_name='post',
            name='reservations',
            field=models.ManyToManyField(blank=True, related_name='reserved_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
