# Generated by Django 4.2.5 on 2024-01-06 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0011_remove_post_is_reserved_remove_post_reservations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reservations',
            field=models.ManyToManyField(related_name='book_reservations', through='mysite.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
