# Generated by Django 4.2.5 on 2024-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_post_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='已預約'),
        ),
    ]
