# Generated by Django 4.2.5 on 2024-01-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_post_is_reserved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='mysite.post'),
        ),
    ]
