# Generated by Django 4.2.5 on 2024-01-10 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0014_alter_reservation_options_alter_reservation_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        migrations.AddField(
            model_name='borrowingrecord',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.post'),
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
