# Generated by Django 4.2.5 on 2024-01-10 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0015_borrowingrecord_remove_post_is_reserved_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='post',
            name='borrowing_records',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='mysite.borrowingrecord'),
        ),
    ]
