# Generated by Django 4.2.5 on 2024-01-10 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0016_remove_post_is_reserved_post_borrowing_records_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_reserved',
        ),
        migrations.AlterField(
            model_name='post',
            name='reservations',
            field=models.ManyToManyField(blank=True, related_name='reserved_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
